<?PHP

$user_ip_adress_min[] = "176.28.80.1";
$user_ip_adress_max[] = "176.28.87.255";
$user_ip_adress_name[] = "bakcell";
$user_ip_adress_min[] = "85.132.57.1";
$user_ip_adress_max[] = "85.132.57.255";
$user_ip_adress_name[] = "bakcell";
$user_ip_adress_min[] = "217.168.176.0";
$user_ip_adress_max[] = "217.168.191.255";
$user_ip_adress_name[] = "azercell";
$user_ip_adress_min[] = "77.244.112.1";
$user_ip_adress_max[] = "77.244.127.255";
$user_ip_adress_name[] = "azerfon";


?>