<?
$smiles_array = array(
".s0.",
".s2.",
".s3.",
".s4.",
".s5.",
".s6.",
".s7.",
".s8.",
".s9.",
".s10.",
".s11.",
".s12.",
".s13.",
".s14.",
".s15.",
".s16.",
".s17.");
$smile = array(
"<img src=\"smile/salam.gif\" alt=\"s0\"/>",
"<img src=\"smile/1.gif\" alt=\"s2\"/>",
"<img src=\"smile/2.gif\" alt=\"s3\"/>",
"<img src=\"smile/5.gif\" alt=\"s4\"/>",
"<img src=\"smile/bad3.gif\" alt=\"s5\"/>",
"<img src=\"smile/bad4.gif\" alt=\"s6\"/>",
"<img src=\"smile/bad2.gif\" alt=\"s7\"/>",
"<img src=\"smile/cool3.gif\" alt=\"s8\"/>",
"<img src=\"smile/cvetok.gif\" alt=\"s9\"/>",
"<img src=\"smilean/4mak.gif\" alt=\"s10\"/>",
"<img src=\"smile/zg.gif\" alt=\"s11\"/>",
"<img src=\"smilean/baby.gif\" alt=\"s12\"/>",
"<img src=\"smilean/dance.gif\" alt=\"s13\"/>",
"<img src=\"smilean/dance3.gif\" alt=\"s14\"/>",
"<img src=\"smilean/good.gif\" alt=\"s15\"/>",
"<img src=\"smilean/haha.gif\" alt=\"s16\"/>",
"<img src=\"smilean/hlop.gif\" alt=\"s17\"/>");
?>
