<?PHP
ERROR_REPORTING(0);
$SES = $_GET['ses'];
if ($SES == '') 
{
$FAIZ = '';
}else {
$FAIZ = ''.$SES.' %';
}
if (100 < $SES) 
{
$FAIZ = '100 %';
}
HEADER( 'Content-type: image/gif' );
	$SIZE = IMAGECREATE( 100, 13 );
	$COLOR = IMAGECOLORALLOCATE( $SIZE, 0, 0, 0 );
	$COLOR1 = IMAGECOLORALLOCATE( $SIZE, 255, 50, 0 );
$COLOR2 = IMAGECOLORALLOCATE( $SIZE, 0, 100, 225 );
	$COLOR3 = IMAGECOLORALLOCATE( $SIZE, 255, 255, 255 );
	IMAGEFILL( $SIZE, 100, 0, $COLOR2 );
	IMAGEFILLEDRECTANGLE( $SIZE, 0, 0, $SES, 13, $COLOR1 );
	IMAGESTRING( $SIZE, 2, 30, 0, '' . $FAIZ . '', $COLOR3 );
	IMAGERECTANGLE( $SIZE, 0, 0, 99, 12, $COLOR );
IMAGEPNG( $SIZE );

?>