<?php

	$user_ip_adress_min[] = '176.28.80.1';
	$user_ip_adress_max[] = '176.28.87.255';
	$user_ip_adress_name[] = 'bakcell';
	$user_ip_adress_name_max[] = '176.28.';
	$user_ip_adress_min[] = '5.44.32.0';
	$user_ip_adress_max[] = '5.44.39.255';
	$user_ip_adress_name[] = 'bakcell';
	$user_ip_adress_name_max[] = '5.44.3';
	$user_ip_adress_min[] = '217.168.176.0';
	$user_ip_adress_max[] = '217.168.200.255';
	$user_ip_adress_name[] = 'azercell';
	$user_ip_adress_name_max[] = '217.168.';
	$user_ip_adress_min[] = '5.191.0.0';
	$user_ip_adress_max[] = '5.191.0.16';
	$user_ip_adress_name[] = 'azercell';
	$user_ip_adress_name_max[] = '5.191.0';
	$user_ip_adress_min[] = '77.244.112.1';
	$user_ip_adress_max[] = '77.244.127.255';
	$user_ip_adress_name[] = 'azerfon';
	$user_ip_adress_name_max[] = '77.244.1';
	$user_ip_adress_min[] = '141.0.9.99';
	$user_ip_adress_max[] = '141.0.10.0';
	$user_ip_adress_name[] = 'bakcell';
	$user_ip_adress_name_max[] = '141.0.';
	$opera_ip = null;
	$opera_ip[] = array( '141.0.8.0', '141.0.11.255', 'opera' );
	$opera_ip[] = array( '185.26.180.0', '185.26.182.63', 'opera' );
	$opera_ip[] = array( '82.145.220.0', '82.145.223.255', 'opera' );
	$opera_ip[] = array( '82.145.208.0', '82.145.215.255', 'opera' );
	$opera_ip[] = array( '82.145.216.0', '82.145.219.255', 'opera' );
?>